name: guess_word_game_api
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_static: ^1.1.2

dev_dependencies:
  http: ^0.13.0
  lints: ^4.0.0
